name: folia-optimized

on:
  workflow_dispatch:  # Позволяет вручную запускать workflow через интерфейс GitHub
  schedule:
    - cron: "0 12 * * *"  # Сборка в 12:00 по Киеву (UTC+3 летом)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Устанавливаем глобальные настройки Git
      - name: Set the git information
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Бот с официальным email

      # Клонируем репозиторий
      - uses: actions/checkout@v4

      # Устанавливаем JDK 21
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      # Настроим временную зону на Киев
      - name: Set timezone to Kyiv
        run: |
          sudo timedatectl set-timezone Europe/Kiev

      # Клонируем репозиторий и применяем патчи
      - name: Clone Folia repo and apply patches
        run: |
          git clone https://github.com/PaperMC/Folia.git ~/folia
          cd ~/folia

      # Получаем список всех веток в репозитории
      - name: Get all branches
        id: branches
        run: |
          git fetch --all
          branches=$(git branch -r | grep -v '\->' | sed 's/origin\///' | tr '\n' ' ')
          echo "::set-output name=branches::${branches}"

      # Сборка всех веток, полученных из предыдущего шага
      - name: Build and release for each branch
        run: |
          # Создаём общий релиз с тегом, если его нет
          RELEASE_NAME="Release-All-Branches-${BUILD_DATE}"
          TAG_NAME="release-all-${BUILD_DATE}"

          release_exists=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/PaperMC/Folia/releases/tags/${TAG_NAME})

          if [[ "$(echo $release_exists | jq -r '.message')" == "Not Found" ]]; then
            # Создаем новый релиз с тегом, если релиз с таким тегом ещё не существует
            release_response=$(curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{
                    "tag_name": "'"${TAG_NAME}"'",
                    "name": "'"${RELEASE_NAME}"'",
                    "draft": false,
                    "prerelease": false
                  }' \
              https://api.github.com/repos/PaperMC/Folia/releases)
          else
            echo "Release with tag ${TAG_NAME} already exists"
          fi

          # Сборка всех веток и загрузка результатов в общий релиз
          for branch in ${{ steps.branches.outputs.branches }}; do
            echo "Building branch: $branch"
            git checkout $branch
            ./gradlew applyPatches
            ./gradlew createMojmapPaperclipJar
            BUILD_DATE=$(date +'%Y-%m-%d')
            JAR_NAME=$(ls build/libs/ | grep paperclip)

            # Получаем URL для загрузки
            upload_url=$(echo "$release_response" | jq -r '.upload_url' | sed 's/{?name,label}//')

            # Загружаем собранный JAR файл как asset в общий релиз
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/java-archive" \
              --data-binary @build/libs/$JAR_NAME \
              "$upload_url?name=$branch-$JAR_NAME"
          done
