name: folia-custom

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс GitHub
  schedule:
    - cron: "0 12 * * *"  # Сборка в 12:00 по Киеву (UTC+3 летом)

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name_default: ${{ steps.upload_release_default.outputs.asset_name }}
      artifact_name_1_19_4: ${{ steps.upload_release_1_19_4.outputs.asset_name }}
      artifact_name_1_20_4: ${{ steps.upload_release_1_20_4.outputs.asset_name }}

    steps:
      - name: Set the git information
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - uses: actions/checkout@v4

      # Устанавливаем JDK 21
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      # Настроим временную зону на Киев
      - name: Set timezone to Kyiv
        run: |
          sudo timedatectl set-timezone Europe/Kiev

      # Клонируем репозиторий и применяем патчи для основной ветки
      - name: Clone Folia repo and apply patches (default branch)
        run: |
          git clone https://github.com/PaperMC/Folia.git ~/folia
          cd ~/folia
          git checkout master
          ./gradlew applyPatches
          ./gradlew createMojmapPaperclipJar

      # Получаем дату сборки
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Получаем имя собранного JAR файла для основной ветки
      - name: Get jar file name for default branch
        id: get_name_default
        run: echo "::set-output name=name::$(ls ~/folia/build/libs/ | grep paperclip)"

      # Сборка для ветки ver/1.19.4
      - name: Build for ver/1.19.4
        run: |
          git clone https://github.com/PaperMC/Folia.git ~/folia-1.19.4
          cd ~/folia-1.19.4
          git checkout ver/1.19.4
          ./gradlew applyPatches
          ./gradlew createMojmapPaperclipJar

      # Получаем имя собранного JAR файла для ветки ver/1.19.4
      - name: Get jar file name for ver/1.19.4
        id: get_name_1_19_4
        run: echo "::set-output name=name::$(ls ~/folia-1.19.4/build/libs/ | grep paperclip)"

      # Сборка для ветки ver/1.20.4
      - name: Build for ver/1.20.4
        run: |
          git clone https://github.com/PaperMC/Folia.git ~/folia-1.20.4
          cd ~/folia-1.20.4
          git checkout ver/1.20.4
          ./gradlew applyPatches
          ./gradlew createMojmapPaperclipJar

      # Получаем имя собранного JAR файла для ветки ver/1.20.4
      - name: Get jar file name for ver/1.20.4
        id: get_name_1_20_4
        run: echo "::set-output name=name::$(ls ~/folia-1.20.4/build/libs/ | grep paperclip)"

      # Create a new release (this step is required to get the upload_url)
      - name: Create GitHub release
        id: create_release_default
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          body: "Release generated by GitHub Actions"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Загружаем JAR файл для основной ветки
      - name: Upload Release Asset for default branch
        id: upload_release_default
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_default.outputs.upload_url }}
          asset_path: /home/runner/folia/build/libs/${{ steps.get_name_default.outputs.name }}
          asset_name: ${{ steps.get_name_default.outputs.name }}
          asset_content_type: application/java-archive

      # Загружаем JAR файл для ветки ver/1.19.4
      - name: Upload Release Asset for ver/1.19.4
        id: upload_release_1_19_4
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_default.outputs.upload_url }}
          asset_path: /home/runner/folia-1.19.4/build/libs/${{ steps.get_name_1_19_4.outputs.name }}
          asset_name: ${{ steps.get_name_1_19_4.outputs.name }}
          asset_content_type: application/java-archive

      # Загружаем JAR файл для ветки ver/1.20.4
      - name: Upload Release Asset for ver/1.20.4
        id: upload_release_1_20_4
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_default.outputs.upload_url }}
          asset_path: /home/runner/folia-1.20.4/build/libs/${{ steps.get_name_1_20_4.outputs.name }}
          asset_name: ${{ steps.get_name_1_20_4.outputs.name }}
          asset_content_type: application/java-archive

    permissions:
      contents: write
